# model_path: "runs/detect/train4/weights/best.pt"
# model_path: "dev/runs/detect/train8/weights/best.pt"
model_path: "yolov9c.pt"
camera_index: 0
voice_index: 1
# imgsize no funciona para inferencia en imagenes, toma el size de la imagen
imgsz: 640
gpu: true
confidence_threshold: 0.60
class_names:
  # Custom Dataset
  0: "an apple"
  1: "a banana"
  2: "a Green Apple"
  3: "an Orange"
  
  47: "an apple"
  46: "a banana"
  51: "a carrot"
  49: "an orange"
  50: "a broccoli"
  40: "a wine glass"